### ISSUE TITLE
Can the algorithm be applied on single-cell RNA seq data?

### ISSUE THREAD

**Issue by rpisalive** [MolecularBioinformatics/GEMCAT#36]
Hello team,

Thanks a lot for developing the great tool and look forward to the paper publication!
For transcriptomic data, may I ask if the algorithm is applicable to single-cell RNA seq data?
Compared to the bulk one, the gene expression matrix of the single-cell one would have a much higher sparsity.
So I wonder if this could affect the accuracy of the algorithm.

Thank you very much!

**Comment by inesheiland** [comment]
Hi,

we have not tried to use it for single cell RNASeq data. We did, however, observe that scarce data does usually not yield high prediction accuracy. That said we had good predictions with a proteomics dataset covering 150 enzymes in the network. But I would expect single cell RNASeq data to have even less coverage. At the end it is dependent on whether or not there are strong changes in particular enzymes and whether or not these are captured in the RNASeq.

Best regards,

Ines
